### PR TITLE
Extra endpoints

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@coderabbitai review

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
### 🔄 The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! 🕰️

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 0. Check out the updates in [your profile](https://github.com/race-of-sloths/u/akorchyn)! 🎊

**Pull request merged**
